/**
 * Audit event types for enterprise compliance
 */

export enum AuditEventType {
  // Authentication events
  USER_LOGIN = 'user.login',
  USER_LOGOUT = 'user.logout',
  USER_LOGIN_FAILED = 'user.login.failed',
  USER_REGISTER = 'user.register',
  USER_PASSWORD_CHANGE = 'user.password.change',
  USER_PASSWORD_RESET = 'user.password.reset',

  // Transaction events
  TRANSACTION_CREATE = 'transaction.create',
  TRANSACTION_SIGN = 'transaction.sign',
  TRANSACTION_BROADCAST = 'transaction.broadcast',
  TRANSACTION_APPROVE = 'transaction.approve',
  TRANSACTION_REJECT = 'transaction.reject',
  TRANSACTION_FAIL = 'transaction.fail',

  // Key management events
  KEY_GENERATE = 'key.generate',
  KEY_IMPORT = 'key.import',
  KEY_EXPORT = 'key.export',
  KEY_BACKUP = 'key.backup',
  KEY_RESTORE = 'key.restore',
  KEY_DELETE = 'key.delete',
  KEY_ROTATE = 'key.rotate',

  // Approval workflow events
  WORKFLOW_CREATE = 'workflow.create',
  WORKFLOW_APPROVE = 'workflow.approve',
  WORKFLOW_REJECT = 'workflow.reject',
  WORKFLOW_EXECUTE = 'workflow.execute',
  WORKFLOW_CANCEL = 'workflow.cancel',

  // Policy events
  POLICY_CREATE = 'policy.create',
  POLICY_UPDATE = 'policy.update',
  POLICY_DELETE = 'policy.delete',
  POLICY_VIOLATION = 'policy.violation',
  POLICY_OVERRIDE = 'policy.override',

  // Role and permission events
  ROLE_ASSIGN = 'role.assign',
  ROLE_REVOKE = 'role.revoke',
  PERMISSION_GRANT = 'permission.grant',
  PERMISSION_REVOKE = 'permission.revoke',

  // Admin events
  ADMIN_LOGIN = 'admin.login',
  ADMIN_LOGOUT = 'admin.logout',
  ADMIN_CONFIG_CHANGE = 'admin.config.change',
  ADMIN_USER_CREATE = 'admin.user.create',
  ADMIN_USER_DELETE = 'admin.user.delete',
  ADMIN_USER_SUSPEND = 'admin.user.suspend',

  // Security events
  SECURITY_ALERT = 'security.alert',
  SECURITY_BREACH_ATTEMPT = 'security.breach.attempt',
  SECURITY_MALICIOUS_ACTIVITY = 'security.malicious',
  SECURITY_UNAUTHORIZED_ACCESS = 'security.unauthorized',

  // System events
  SYSTEM_START = 'system.start',
  SYSTEM_SHUTDOWN = 'system.shutdown',
  SYSTEM_ERROR = 'system.error',
  SYSTEM_BACKUP = 'system.backup',
  SYSTEM_RESTORE = 'system.restore',
}

export interface AuditEvent {
  id: string
  eventType: AuditEventType
  userId?: string
  username?: string
  ipAddress?: string
  userAgent?: string
  timestamp: Date
  metadata?: Record<string, unknown>
  severity: 'low' | 'medium' | 'high' | 'critical'
  status: 'success' | 'failure' | 'pending'
  resourceId?: string
  resourceType?: string
}

export interface AuditFilter {
  userId?: string
  eventType?: AuditEventType | AuditEventType[]
  startDate?: Date
  endDate?: Date
  severity?: AuditEvent['severity'][]
  status?: AuditEvent['status'][]
  resourceId?: string
  resourceType?: string
  limit?: number
  offset?: number
}

export interface AuditStorage {
  write(event: AuditEvent): Promise<void>
  query(filters: AuditFilter): Promise<AuditEvent[]>
  count(filters: AuditFilter): Promise<number>
  export(filters: AuditFilter, format: 'csv' | 'json'): Promise<string>
  clearOldEvents(beforeDate: Date): Promise<number>
}

export interface AuditLoggerConfig {
  storage: AuditStorage
  enableConsole?: boolean
  minSeverity?: AuditEvent['severity']
  batchSize?: number
  flushInterval?: number
}

/**
 * Compliance data generated by audit logger
 * Used as input for full compliance reports
 */
export interface AuditComplianceData {
  period: {
    start: Date
    end: Date
  }
  totalEvents: number
  eventsByType: Record<string, number>
  eventsByUser: Record<string, number>
  eventsBySeverity: Record<string, number>
  securityEvents: AuditEvent[]
  policyViolations: AuditEvent[]
  adminActions: AuditEvent[]
}

export interface AuditSummary {
  totalEvents: number
  eventCounts: Record<AuditEventType, number>
  userActivity: Record<string, number>
  securityIncidents: number
  policyViolations: number
  lastActivity: Date | null
}
